---
title: "512 Project"
author: "Nolan Walker"
date: "2/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,fig.height=10,fig.width=20,echo=TRUE,eval=TRUE}
library(tidyverse)
library(dendextend)
library(reshape2)
library(tibble)
library(purrr)
library(ape)
library(knitr)
library(broom)
library(caret)
library(bnstruct)
data<-read.csv("C:/Users/Nolan/Downloads/Data_Cortex_Nuclear.csv")
#str(data)
par(mfrow=c(3,3))
for (i in 1:77)
  {
   boxplot(data[,i+1]~data$class,xlab="class",ylab="protein levels",na_)
  title(main=names(data)[i+1])
}
data.col<-data[,2:78]
data.knn<-preProcess(data.col,method=c("knnImpute"),k=20,knnSummary = mean)
impute_info<-predict(data.knn,data.col,na.action=na.pass)
col.names <- data.frame(col = names(data.knn$mean), mean = data.knn$mean, sd = data.knn$std)
for(i in col.names$col){
 impute_info[i] <- impute_info[i]*data.knn$std[i]+data.knn$mean[i] 
}
Data<-data.frame(impute_info,data$class)
#data.no.na<-na.omit(data)
#data.nona<-apply(data,2,function(x){ifelse(sum(!is.na(x))<901,,)})
# Data <- data %>%
#   group_by(class) %>%
#   mutate_each(funs(replace(., which(is.na(.)), mean(., na.rm=TRUE)))) %>%
#   as.data.frame() 

proteins <- names(Data[1:77])
classes <- as.vector(unique(as.character(Data$class))) #creating list of classes names


aov_test <- function(prot){
  return(aov(eval(parse(text = prot)) ~ class, Data) %>% tidy())
}

AOV_df <- data.frame(matrix(NA, nrow = length(proteins), ncol = 3))
names(AOV_df) <- c("Protein", "Var_expl", "p.value")
alpha = 0.01

for(i in 1:length(proteins)){
  cat("#### ", proteins[i], "\n")
  AOV <- aov_test(proteins[i])
  AOV_df$Protein[i] <- proteins[i]
  AOV_df$Var_expl[i] <- round(AOV$sumsq[1] / (AOV$sumsq[1] + AOV$sumsq[2]), 2)
  AOV_df$p.value[i] <- AOV$p.value
  cat(paste0("Total variability: ", round(AOV$sumsq[1] + AOV$sumsq[2], 2)))
  cat('\n\n')
  cat(paste0("Percentage of explained variability for ", proteins[i], " mean differences: ", round(AOV$sumsq[1] * 100 / (AOV$sumsq[1] + AOV$sumsq[2]), 2), "%"))
  cat('\n\n')
  cat(paste0("P value for ", proteins[i], " mean differences: ", round(AOV$p.value[1], 5)))
  cat('\n\n')
}

AOV_df$reject_null <- AOV_df$p.value < alpha
alpha_adj <- alpha / length(unique(Data$class))*(length(unique(Data$class))-1)/2
```

